version: '3.9'
services:
  backend:
    build: ./backend
    container_name: "backend-mf-container"
    ports :
      - 5000:5000
    networks:
      - formation-management
    volumes:
      - ./backend:/home/backend
    
  front-end :
    build: ./frontend
    container_name: "front-end-mf-container"
    ports:
      - 5173:5173
    networks:
      - formation-management
    volumes:
      - ./frontend:/home/front-end-vite

  
networks:
  formation-management:
    driver: bridge